<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.15.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cyrene.Core.Bridge\Cyrene.Core.Bridge.csproj" />
    <ProjectReference Include="..\Cyrene.PluginSdk\Cyrene.PluginSdk.csproj" />
  </ItemGroup>

</Project>
