const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const component = fs.readFileSync(path.join(root, 'src', 'components', 'SecondarySidebarMenu.vue'), 'utf8')
const router = fs.readFileSync(path.join(root, 'src', 'router', 'index.js'), 'utf8')
const settingsLayout = fs.readFileSync(path.join(root, 'src', 'views', 'SettingsLayoutView.vue'), 'utf8')
const settingsView = fs.readFileSync(path.join(root, 'src', 'views', 'SettingsView.vue'), 'utf8')
const appLayout = fs.readFileSync(path.join(root, 'src', 'components', 'layout', 'AppLayout.vue'), 'utf8')
const navigationDock = fs.readFileSync(path.join(root, 'src', 'components', 'layout', 'NavigationDock.vue'), 'utf8')
const globalCss = fs.readFileSync(path.join(root, 'src', 'assets', 'global.css'), 'utf8')

test('secondary menu exposes route-aware overlay navigation', () => {
  assert.match(component, /defineProps\(/)
  assert.match(component, /open:/)
  assert.match(component, /initialRoute/)
  assert.match(component, /navigateOnOpen:/)
  assert.match(component, /item\.id === props\.initialRoute/)
  assert.match(component, /props\.items\[0\]/)
  assert.match(component, /if \(props\.navigateOnOpen && target/)
  assert.match(component, /defineEmits\(\['back'\]\)/)
  assert.match(component, /translateX\(100%\)/)
  assert.match(component, /secondary-sidebar-menu__back/)
  assert.match(component, /overflow-x:\s*hidden/)
})

test('settings routes expose nested child pages and a default child redirect', () => {
  assert.match(router, /path: '\/settings'[\s\S]*?name: 'Settings'/)
  assert.match(router, /children:/)
  assert.match(router, /path: ''\s*,\s*redirect:/)
  assert.match(router, /path: 'general'/)
  assert.match(router, /path: 'appearance'/)
  assert.match(router, /path: 'features'/)
  assert.match(router, /path: 'data'/)
  assert.match(router, /path: 'performance'\s*,\s*redirect: '\/settings\/appearance'/)
  assert.match(router, /path: 'balance'\s*,\s*redirect: '\/settings\/features'/)
  assert.match(router, /path: 'changelog'\s*,\s*redirect: '\/settings\/data'/)
  assert.match(settingsLayout, /<router-view[\s\S]*Component[\s\S]*route/)
  assert.match(settingsLayout, /name="page-forward"/)
  assert.match(settingsLayout, /mode="out-in"/)
  assert.doesNotMatch(settingsLayout, /settings-subpage-slide/)
  assert.match(globalCss, /\.page-forward-enter-active/)
  assert.doesNotMatch(settingsLayout, /SecondarySidebarMenu/)
  assert.match(appLayout, /route\.matched\[0\]\?\.path \|\| route\.path/)
})

test('settings secondary menu overlays the existing primary navigation dock', () => {
  assert.match(navigationDock, /SecondarySidebarMenu/)
  assert.match(navigationDock, /settingsMenuItems/)
  assert.match(navigationDock, /:collapsed="dockCollapsed"/)
  assert.match(navigationDock, /@back=/)
  assert.match(component, /position:\s*absolute/)
  assert.match(component, /inset:\s*0/)
  assert.match(component, /translateX\(100%\)/)
  assert.match(component, /is-open/)
})

test('secondary menu keeps one DOM instance so open and close transitions can run', () => {
  const usage = navigationDock.match(/<SecondarySidebarMenu[\s\S]*?\/>/)?.[0] || ''
  assert.doesNotMatch(usage, /:key="activeSecondaryMenu \|\| 'closed'"/)
})

test('settings navigation exposes four broad sections without another menu level', () => {
  assert.match(navigationDock, /to: '\/settings\/general'/)
  assert.match(navigationDock, /to: '\/settings\/appearance'/)
  assert.match(navigationDock, /to: '\/settings\/features'/)
  assert.match(navigationDock, /to: '\/settings\/data'/)
  assert.doesNotMatch(navigationDock, /id: 'application'/)
  assert.doesNotMatch(navigationDock, /children:/)
  assert.doesNotMatch(component, /openGroup/)
  assert.equal((settingsView.match(/v-if="section === 'general'"/g) || []).length, 1)
  assert.equal((settingsView.match(/v-if="section === 'appearance'"/g) || []).length, 2)
  assert.equal((settingsView.match(/v-if="section === 'features'"/g) || []).length, 2)
  assert.equal((settingsView.match(/v-if="section === 'data'"/g) || []).length, 2)
})

test('secondary menu has no title and collapses navigation labels to icons', () => {
  assert.match(component, /collapsed:/)
  assert.match(component, /is-collapsed/)
  assert.match(component, /secondary-sidebar-menu__back-label/)
  assert.match(component, /secondary-sidebar-menu__item-label/)
  assert.match(component, /\.secondary-sidebar-menu\.is-collapsed[\s\S]*secondary-sidebar-menu__back-label/)
  assert.match(component, /\.secondary-sidebar-menu\.is-collapsed[\s\S]*secondary-sidebar-menu__item-label/)
  assert.match(component, /secondary-sidebar-menu__back-label[^}]*white-space:\s*nowrap/)
  assert.match(component, /secondary-sidebar-menu__item-label[^}]*white-space:\s*nowrap/)
  assert.doesNotMatch(component, /secondary-sidebar-menu__heading/)
  assert.doesNotMatch(component, /title:\s*{\s*type:\s*String/)
  const usage = navigationDock.match(/<SecondarySidebarMenu[\s\S]*?\/>/)?.[0] || ''
  assert.doesNotMatch(usage, /:title=/)
})
